







































































































































































































WM error: 0.072%, RM error 84.127%, loss: 0.6316: 100%|████████████████████████████████████████████████████████████████████████████████████████| 200/200 [3:12:51<00:00, 57.86s/it]
Traceback (most recent call last):
  File "main.py", line 296, in <module>
    experiment(config=vars(args))
  File "main.py", line 251, in experiment
    wandb.save("*rate_maps.pt")
  File "C:\Users\bryce\anaconda3\envs\nmda\lib\site-packages\wandb\sdk\wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\bryce\anaconda3\envs\nmda\lib\site-packages\wandb\sdk\wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\bryce\anaconda3\envs\nmda\lib\site-packages\wandb\sdk\wandb_run.py", line 1933, in save
    resolved_glob_path = glob_path.resolve()
  File "C:\Users\bryce\anaconda3\envs\nmda\lib\pathlib.py", line 1181, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\bryce\anaconda3\envs\nmda\lib\pathlib.py", line 206, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '*rate_maps.pt'